language: python
python:
  - '3.6'
  - '3.7'
install:
  - python -m pip install --upgrade pip
  - python setup.py install
  - python -m pip install -r requirements_test.txt
before_script:
  - sudo mkdir -p /nfs/ftp/pub/databases/ena/wgs/public/
  - for i in `ls -1 tests/data/dat`; do A=`echo "${i:0:2}" | awk '{print tolower($0)}'`; C="/nfs/ftp/pub/databases/ena/wgs/public/${A}"; sudo mkdir -p $C; sudo ln -s `pwd`/tests/data/dat/${i} $C; done
script:
  - python -m pytest --cov=ga4gh/ --cov-report=term-missing tests/
after_success:
  - coveralls
after_script:
  - kill %1